POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjIzODczZDQwMmNkYjBhZWQwOWRjNmM5IiwiaWF0IjoxNjQ3ODc0NDUxfQ.QpI5XkQampVwaSvOIaYKkEWoN4pBPxl3cvqFRupyMm4

{
    "url": "http://motorsportworld.com/blogs/ajones/fieryferrari",
    "title": "Fiery Ferrari",
    "author": "Alan Jones",
    "likes": 1403
}